[project]
authors = ["David Shipman <dshipman@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tb_hierarchical"
platforms = ["win-64","linux-64","osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
ipykernel = ">=7.1.0,<8"
pymc = "==5.2.0"
ipython = ">=8.37.0,<9"
openpyxl = ">=3.1.5,<4"
pyarrow = ">=21.0.0,<22"
gitpython = ">=3.1.45,<4"
ipyfilechooser = ">=0.6.0,<0.7"
jinja2 = ">=3.1.6,<4"
jupyter = ">=1.1.1,<2"
pyyaml = ">=6.0.3,<7"
tabulate = ">=0.9.0,<0.10"

[pypi-dependencies]
tbh = { path = "./code", editable = true}
pyyaml = ">=6.0.2, <7"
arviz = ">=0.21.0, <0.22"
estival = { version = "==0.6.0a", extras = ["nevergrad"] }
ipywidgets = ">=8.1.7, <9"
summerepi2 = { git = "https://github.com/monash-emu/summer2gen.git" }
